import { User } from '@/interfaces/user';

export const users: User[] = [
  {
    id: 1,
    name: 'Omar Adel',
    email: 'omar.adel@example.com',
    role: 'Admin',
    status: 'Active',
    city: 'Cairo',
  },
  {
    id: 2,
    name: 'Mona Sameh',
    email: 'mona.sameh@example.com',
    role: 'Editor',
    status: 'Inactive',
    city: 'Giza',
  },
  {
    id: 3,
    name: 'Youssef Magdy',
    email: 'youssef.magdy@example.com',
    role: 'Viewer',
    status: 'Active',
    city: 'Alexandria',
  },
  {
    id: 4,
    name: 'Laila Hany',
    email: 'laila.hany@example.com',
    role: 'Admin',
    status: 'Inactive',
    city: 'Cairo',
  },
  {
    id: 5,
    name: 'Karim Fathy',
    email: 'karim.fathy@example.com',
    role: 'Editor',
    status: 'Active',
    city: 'Giza',
  },
  {
    id: 6,
    name: 'Nour Ahmed',
    email: 'nour.ahmed@example.com',
    role: 'Viewer',
    status: 'Active',
    city: 'Tanta',
  },
  {
    id: 7,
    name: 'Ali Sherif',
    email: 'ali.sherif@example.com',
    role: 'Admin',
    status: 'Inactive',
    city: 'Cairo',
  },
  {
    id: 8,
    name: 'Sara Nabil',
    email: 'sara.nabil@example.com',
    role: 'Viewer',
    status: 'Active',
    city: 'Mansoura',
  },
  {
    id: 9,
    name: 'Tamer Yassin',
    email: 'tamer.yassin@example.com',
    role: 'Editor',
    status: 'Active',
    city: 'Alexandria',
  },
  {
    id: 10,
    name: 'Rania Adel',
    email: 'rania.adel@example.com',
    role: 'Viewer',
    status: 'Inactive',
    city: 'Aswan',
  },
  {
    id: 11,
    name: 'Hassan Emad',
    email: 'hassan.emad@example.com',
    role: 'Admin',
    status: 'Active',
    city: 'Giza',
  },
  {
    id: 12,
    name: 'Dina Tarek',
    email: 'dina.tarek@example.com',
    role: 'Editor',
    status: 'Active',
    city: 'Cairo',
  },
  {
    id: 13,
    name: 'Mahmoud Samir',
    email: 'mahmoud.samir@example.com',
    role: 'Viewer',
    status: 'Inactive',
    city: 'Zagazig',
  },
  {
    id: 14,
    name: 'Yasmin Khaled',
    email: 'yasmin.khaled@example.com',
    role: 'Admin',
    status: 'Active',
    city: 'Suez',
  },
  {
    id: 15,
    name: 'Walid Ayman',
    email: 'walid.ayman@example.com',
    role: 'Viewer',
    status: 'Active',
    city: 'Giza',
  },
  {
    id: 16,
    name: 'Noha Osama',
    email: 'noha.osama@example.com',
    role: 'Editor',
    status: 'Inactive',
    city: 'Cairo',
  },
  {
    id: 17,
    name: 'Ahmed Zaki',
    email: 'ahmed.zaki@example.com',
    role: 'Admin',
    status: 'Active',
    city: 'Luxor',
  },
  {
    id: 18,
    name: 'Marwa Sayed',
    email: 'marwa.sayed@example.com',
    role: 'Viewer',
    status: 'Active',
    city: 'Cairo',
  },
  {
    id: 19,
    name: 'Mostafa Nader',
    email: 'mostafa.nader@example.com',
    role: 'Editor',
    status: 'Inactive',
    city: 'Giza',
  },
  {
    id: 20,
    name: 'Huda Fares',
    email: 'huda.fares@example.com',
    role: 'Viewer',
    status: 'Active',
    city: 'Fayoum',
  },
  {
    id: 21,
    name: 'Ziad Islam',
    email: 'ziad.islam@example.com',
    role: 'Admin',
    status: 'Inactive',
    city: 'Cairo',
  },
  {
    id: 22,
    name: 'Farah Yasser',
    email: 'farah.yasser@example.com',
    role: 'Editor',
    status: 'Active',
    city: 'Alexandria',
  },
  {
    id: 23,
    name: 'Hany Gamal',
    email: 'hany.gamal@example.com',
    role: 'Viewer',
    status: 'Active',
    city: 'Giza',
  },
  {
    id: 24,
    name: 'Rana Sobhy',
    email: 'rana.sobhy@example.com',
    role: 'Admin',
    status: 'Inactive',
    city: 'Ismailia',
  },
  {
    id: 25,
    name: 'Sherif Ashraf',
    email: 'sherif.ashraf@example.com',
    role: 'Editor',
    status: 'Active',
    city: 'Cairo',
  },
  {
    id: 26,
    name: 'Nadine Refaat',
    email: 'nadine.refaat@example.com',
    role: 'Viewer',
    status: 'Inactive',
    city: 'Minya',
  },
  {
    id: 27,
    name: 'Alaa Mostafa',
    email: 'alaa.mostafa@example.com',
    role: 'Admin',
    status: 'Active',
    city: 'Giza',
  },
  {
    id: 28,
    name: 'Salma Hesham',
    email: 'salma.hesham@example.com',
    role: 'Viewer',
    status: 'Active',
    city: 'Cairo',
  },
  {
    id: 29,
    name: 'Basem Reda',
    email: 'basem.reda@example.com',
    role: 'Editor',
    status: 'Inactive',
    city: 'Asyut',
  },
  {
    id: 30,
    name: 'Layla Mohamed',
    email: 'layla.mohamed@example.com',
    role: 'Viewer',
    status: 'Active',
    city: 'Alexandria',
  },
];
